project:
  type: website

execute:
  freeze: auto
 
website:
  title: "handbook"
  search: true
  page-navigation: true
  back-to-top-navigation: true
  #output-dir: _site 
  repo-url: https://github.com/rollie-tribytics/handbook
  repo-actions: [edit, source, issue]
  navbar:
    left:
      - href: index.qmd
        icon: "{{< fa brands github >}}"
        text: "Home"
      - about.qmd
      - text: "Presentations"
        href: presentations/demo_presentation.qmd
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: "Home"
      - about.qmd
      - text: "---"
      - section: "Basics"
        contents: 
          - hello.qmd
          - world.qmd
  page-footer: 
    left: "Copyright 2025"
    border: false
    right:
      - icon: github
        href: https://github.com

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



